package org.videolan.vlc.kmp

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.media.ThumbnailUtils
import android.net.Uri
import android.os.Build
import android.provider.MediaStore
import android.util.Size
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.asImageBitmap
import coil3.BitmapImage
import coil3.ImageLoader
import coil3.asImage
import coil3.fetch.FetchResult
import coil3.fetch.Fetcher
import coil3.fetch.ImageFetchResult
import coil3.key.Keyer
import coil3.request.ImageRequest
import coil3.request.Options
import coil3.request.SuccessResult
import coil3.toBitmap
import androidx.core.net.toUri
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.videolan.medialibrary.MLServiceLocator
import org.videolan.medialibrary.interfaces.media.MediaWrapper
import org.videolan.vlc.compose.artwork.ArtworkLoader
import org.videolan.vlc.gui.helpers.AudioUtil.readCoverBitmap
import org.videolan.vlc.util.ThumbnailsProvider
import org.videolan.vlc.util.isSchemeHttpOrHttps
import java.io.File

/**
 * Android artwork decoder using [ThumbnailsProvider] / [BitmapFactory].
 */
class AndroidArtworkLoader(
    context: Context,
) : ArtworkLoader {

    private val appContext = context.applicationContext
    private val imageLoader = ImageLoader.Builder(appContext)
        .components {
            add(NativeThumbnailFetcher.Factory(this@AndroidArtworkLoader), NativeThumbnailData::class)
            add(NativeThumbnailKeyer(), NativeThumbnailData::class)
        }
        .build()

    override suspend fun loadBitmap(uri: String?, widthPx: Int): ImageBitmap? = withContext(Dispatchers.IO) {
        val raw = uri?.trim().orEmpty()
        if (raw.isEmpty()) return@withContext null
        val width = widthPx.coerceIn(48, 1024)
        loadNativeThumbnailThroughCoil(raw, width)?.let { return@withContext it }
        decode(raw, width)?.asImageBitmap()
    }

    /**
     * Native video frames remain generated by MediaStore/LibVLC, but enter Coil as an image
     * result. This gives the Android grid one cache and one request lifecycle instead of
     * decoding the same frame again in every composable.
     */
    private suspend fun loadNativeThumbnailThroughCoil(raw: String, width: Int): ImageBitmap? {
        if (!isVideoSource(raw, runCatching { raw.toUri() }.getOrNull())) return null
        val request = ImageRequest.Builder(appContext)
            .data(NativeThumbnailData(raw, width))
            .size(width, width)
            .build()
        return when (val result = imageLoader.execute(request)) {
            is SuccessResult -> result.image
                .let { image ->
                    (image as? BitmapImage)?.bitmap ?: image.toBitmap(width, width)
                }
                .asImageBitmap()
            else -> null
        }
    }

    private suspend fun decode(raw: String, width: Int): Bitmap? {
        val decoded = runCatching { Uri.decode(raw) }.getOrDefault(raw)
        val parsed = runCatching { raw.toUri() }.getOrElse {
            runCatching { decoded.toUri() }.getOrNull()
        }
        val scheme = parsed?.scheme
        val isVideo = isVideoSource(raw, parsed)

        // Prefer the platform thumbnail service for video content. This also handles content://
        // URIs from the system picker, which cannot be opened as a filesystem path.
        if (isVideo) {
            decodeVideoThumbnail(parsed, decoded, width)?.let { return it }
        }

        // HTTP(S) covers via existing downloader / decoder path.
        if (isSchemeHttpOrHttps(scheme) || isSchemeHttpOrHttps(decoded)) {
            readCoverBitmap(decoded, width)?.let { return it }
        }

        // Prefer ThumbnailsProvider when a MediaWrapper can be built.
        runCatching {
            val wrapper = mediaWrapperFor(raw, parsed, isVideo)
            ThumbnailsProvider.obtainBitmap(wrapper, width)
        }.getOrNull()?.let { return it }

        // file:// or bare filesystem path
        val path = when {
            scheme == "file" -> Uri.decode(parsed.path ?: "")
            decoded.startsWith("file://") -> Uri.decode(decoded.removePrefix("file://"))
            decoded.startsWith("/") -> decoded
            scheme.isNullOrBlank() && !decoded.contains("://") -> decoded
            else -> null
        }
        if (!path.isNullOrBlank()) {
            readCoverBitmap(path, width)?.let { return it }
            val file = File(path)
            if (file.isFile) {
                decodeSampled(file.absolutePath, width)?.let { return it }
            }
        }

        // content:// and other resolvable URIs via ContentResolver
        if (parsed != null && !parsed.scheme.isNullOrBlank() && parsed.scheme != "file") {
            runCatching {
                appContext.contentResolver.openInputStream(parsed)?.use { input ->
                    val bounds = BitmapFactory.Options().apply { inJustDecodeBounds = true }
                    BitmapFactory.decodeStream(input, null, bounds)
                    bounds
                }?.let { bounds ->
                    appContext.contentResolver.openInputStream(parsed)?.use { input ->
                        val opts = BitmapFactory.Options().apply {
                            inSampleSize = calculateInSampleSize(bounds.outWidth, bounds.outHeight, width)
                        }
                        BitmapFactory.decodeStream(input, null, opts)
                    }
                }
            }.getOrNull()?.let { return it }
        }

        // Last resort: treat raw string as a local cover path.
        return readCoverBitmap(decoded, width)
    }

    private suspend fun decodeNativeThumbnail(raw: String, width: Int): Bitmap? {
        val decoded = runCatching { Uri.decode(raw) }.getOrDefault(raw)
        val parsed = runCatching { raw.toUri() }.getOrElse {
            runCatching { decoded.toUri() }.getOrNull()
        }
        if (!isVideoSource(raw, parsed)) return null
        decodeVideoThumbnail(parsed, decoded, width)?.let { return it }
        return runCatching {
            ThumbnailsProvider.obtainBitmap(mediaWrapperFor(raw, parsed, isVideo = true), width)
        }.getOrNull()
    }

    private fun mediaWrapperFor(raw: String, parsed: Uri?, isVideo: Boolean): MediaWrapper {
        val uri = parsed ?: runCatching { raw.toUri() }.getOrElse { Uri.parse(raw) }
        return MLServiceLocator.getAbstractMediaWrapper(uri).apply {
            if (isVideo) {
                // ThumbnailsProvider only generates a frame when the wrapper is a video and has
                // no cover art. Do not turn the media URI into artworkURL before that check.
                type = MediaWrapper.TYPE_VIDEO
            } else if (artworkURL.isNullOrBlank()) {
                artworkURL = raw
            }
            if (type == MediaWrapper.TYPE_ALL) {
                type = MediaWrapper.TYPE_AUDIO
            }
        }
    }

    private fun isVideoSource(raw: String, parsed: Uri?): Boolean {
        val mime = parsed?.let { uri ->
            runCatching { appContext.contentResolver.getType(uri) }.getOrNull()
        }
        if (mime?.startsWith("video/", ignoreCase = true) == true) return true
        val path = (parsed?.path ?: Uri.decode(raw)).substringBefore('?').lowercase()
        return VIDEO_EXTENSIONS.any { path.endsWith(it) }
    }

    private fun decodeVideoThumbnail(parsed: Uri?, decoded: String, width: Int): Bitmap? {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q && parsed?.scheme == "content") {
            runCatching {
                appContext.contentResolver.loadThumbnail(
                    parsed,
                    Size(width, width),
                    null,
                )
            }.getOrNull()?.let { return it }
        }
        val path = when {
            parsed?.scheme == "file" -> Uri.decode(parsed.path.orEmpty())
            decoded.startsWith("file://") -> Uri.decode(decoded.removePrefix("file://"))
            decoded.startsWith("/") -> decoded
            else -> null
        } ?: return null
        return runCatching {
            @Suppress("DEPRECATION")
            ThumbnailUtils.createVideoThumbnail(path, MediaStore.Video.Thumbnails.MINI_KIND)
        }.getOrNull()
    }

    private fun decodeSampled(path: String, width: Int): Bitmap? {
        val bounds = BitmapFactory.Options().apply { inJustDecodeBounds = true }
        BitmapFactory.decodeFile(path, bounds)
        val opts = BitmapFactory.Options().apply {
            inSampleSize = calculateInSampleSize(bounds.outWidth, bounds.outHeight, width)
        }
        return BitmapFactory.decodeFile(path, opts)
    }

    private fun calculateInSampleSize(width: Int, height: Int, reqWidth: Int): Int {
        if (width <= 0 || height <= 0 || reqWidth <= 0) return 1
        var inSampleSize = 1
        if (width > reqWidth || height > reqWidth) {
            val halfWidth = width / 2
            val halfHeight = height / 2
            while (halfWidth / inSampleSize >= reqWidth && halfHeight / inSampleSize >= reqWidth) {
                inSampleSize *= 2
            }
        }
        return inSampleSize.coerceAtLeast(1)
    }

    private companion object {
        val VIDEO_EXTENSIONS = setOf(
            ".3gp", ".avi", ".flv", ".m4v", ".mkv", ".mov", ".mp4", ".mpeg", ".mpg", ".ogv",
            ".ts", ".webm", ".wmv",
        )
    }

    private data class NativeThumbnailData(
        val source: String,
        val width: Int,
    )

    private class NativeThumbnailKeyer : Keyer<NativeThumbnailData> {
        override fun key(data: NativeThumbnailData, options: Options): String =
            "vlc-native-thumbnail:${data.source}:${data.width}"
    }

    private class NativeThumbnailFetcher(
        private val data: NativeThumbnailData,
        private val loader: AndroidArtworkLoader,
    ) : Fetcher {
        override suspend fun fetch(): FetchResult? = loader
            .decodeNativeThumbnail(data.source, data.width)
            ?.let { bitmap ->
                ImageFetchResult(
                    image = bitmap.asImage(),
                    isSampled = false,
                    dataSource = coil3.decode.DataSource.MEMORY,
                )
            }

        class Factory(
            private val loader: AndroidArtworkLoader,
        ) : Fetcher.Factory<NativeThumbnailData> {
            override fun create(
                data: NativeThumbnailData,
                options: Options,
                imageLoader: ImageLoader,
            ): Fetcher = NativeThumbnailFetcher(data, loader)
        }
    }
}
